/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-05-28

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"

#define LED_PIN GPIO_Pin_13
#define ADC1_CHANNEL_2 2
#define ADC1_CHANNEL_6 6

void GPIO_Config(void);
void ADC_Config(void);
void TIM_Config(uint32_t frequency);

int main(void)
{
    GPIO_Config();
    ADC_Config();
    TIM_Config(0);  // Изначально устанавливаем частоту сигнала на входе 6 канала ADC в 0 Гц

    while (1)
    {
        // Запускаем преобразование ADC
        ADC1->CR |= ADC_CR_ADSTART;

        // Ждем завершения преобразования ADC
        while (!(ADC1->ISR & ADC_ISR_EOC))
        {
        }

        // Получаем значения напряжения с входов 2 и 6 каналов ADC
        uint16_t voltage2 = ADC1->DR;
        uint16_t voltage6 = ADC1->DR;

        // Рассчитываем длительность свечения светодиода в зависимости от напряжения
        uint32_t duration = voltage2 * 100;  // Примерная зависимость: длительность = напряжение * 100

        // Устанавливаем длительность свечения светодиода
        if (duration > 1000)
        {
            duration = 1000;
        }
        TIM3->CCR1 = duration;

        // Устанавливаем частоту сигнала на входе 6 канала ADC
        uint32_t frequency = voltage6 * 10;  // Примерная зависимость: частота = напряжение * 10
        TIM_Config(frequency);
    }
}

void GPIO_Config(void)
{
    RCC->AHBENR |= RCC_AHBENR_GPIOCEN;

    GPIOC->MODER |= GPIO_MODER_MODER13_0;  // Настройка пина PC13 на вывод
    GPIOC->OTYPER &= ~GPIO_OTYPER_OT_13;    // Открытый сток
    GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13_0;  // Скорость I/O - низкая
    GPIOC->PUPDR &= ~GPIO_PUPDR_PUPDR13;    // Отключение подтягивающих резисторов
}

void ADC_Config(void)
{
    RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
    RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;

    GPIOA->MODER |= GPIO_MODER_MODER1;     // Настройка пина PA1 на аналоговый вход (ADC1_IN2)
    GPIOA->MODER |= GPIO_MODER_MODER6;     // Настройка пина PA6 на аналоговый вход (ADC1_IN6)

    ADC1->CFGR1 |= ADC_CFGR1_RES_1;         // Установка разрешения ADC на 8 бит
    ADC1->CHSELR |= ADC_CHSELR_CHSEL2;      // Выбор канала 2 для преобразования
    ADC1->CHSELR |= ADC_CHSELR_CHSEL6;      // Выбор канала 6 для преобразования
    ADC1->CFGR1 |= ADC_CFGR1_CONT;          // Включение непрерывного режима преобразования
    ADC1->CR |= ADC_CR_ADEN;                // Включение ADC

    while (!(ADC1->ISR & ADC_ISR_ADRDY))    // Ожидание готовности ADC
    {
    }

    ADC1->CR |= ADC_CR_ADSTART;             // Запуск преобразования ADC
}

void TIM_Config(uint32_t frequency)
{
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;

    TIM3->PSC = 48000 - 1;                  // Предделитель для получения базовой частоты 1 КГц
    TIM3->ARR = 1000;                       // Максимальное значение счетчика

    TIM3->CCR1 = 0;                         // Изначально длительность свечения светодиода = 0

    TIM3->CCMR1 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2;  // Режим PWM1 на выходе CCR1
    TIM3->CCER |= TIM_CCER_CC1E;            // Разрешение генерации сигнала на выходе CCR1

    TIM3->CR1 |= TIM_CR1_CEN;               // Включение таймера

    TIM3->ARR = 1000 / frequency;           // Установка периода генерации сигнала
}
