/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-05-28

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"
uint32_t pwm_ch3_tim3=0;
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */
void TIM3_IRQHandler() {
if(TIM3->SR & TIM_SR_UIF){
	TIM3->SR &= ~TIM_SR_UIF;
	TIM3->CCR3 = pwm_ch3_tim3;
	pwm_ch3_tim3 += 100;
	if (pwm_ch3_tim3 > TIM3->ARR) {
		pwm_ch3_tim3 = 0;
	}
}
}
void init_tim3_pwm_ch3() {
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN;
	GPIOC->MODER |= GPIO_MODER_MODER8_1;	//AF

	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	TIM3->ARR = 8000;
	TIM3->PSC = 1000;

	//Enable straight pwm mode
	TIM3->CCMR2 |= TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2;	//pwm on
	TIM3->CCER |= TIM_CCER_CC3E;


	TIM3->DIER |= TIM_DIER_UIE;
	NVIC_EnableIRQ(TIM3_IRQn);
	NVIC_SetPriority(TIM3_IRQn, 2);

	TIM3->CR1 |= TIM_CR1_CEN;
}
/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{


  /* TODO - Add your application code here */
init_tim3_pwm_ch3();
  /* Infinite loop */
  while (1)
  {

  }
}
